### ISSUE TITLE
Invalid Grant

### ISSUE THREAD

**Issue by matthewjamesr** [tootsuite/omniauth-mastodon#2]
Hello I keep getting the following issue:

```
invalid_grant: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client. {"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
```

Here is my omniauth.rb initializer:

```
Rails.application.config.middleware.use OmniAuth::Builder do
  callback_url = "http://249f73c6.ngrok.io/auth/mastodon/callback"
  @domain = "https://securitymastod.one"
  provider :mastodon, scope: 'read', credentials: lambda { |domain='securitymastod.one', callback_url='249f73c6.ngrok.io/auth/mastodon/callback'|
    client = Mastodon::REST::Client.new(base_url: "https://securitymastod.one")
    app = client.create_app('Follower Test App', "http://249f73c6.ngrok.io/auth/mastodon/callback")

    return [app.client_id, app.client_secret]
  }
end
```

Also I can only get *read* scope to work. When I do `scope: 'read write'` I get malformed or wrong scope from the instance.

Pleas ignore the variables not being used as I have been fiddling to test the issue.

**Comment by matthewjamesr** [comment]
I have amended my omniauth.rb to the following which fixed scopes but still returns invalid_grant.

```
Rails.application.config.middleware.use OmniAuth::Builder do
  callback_url = "https://8ae29422.ngrok.io/auth/mastodon/callback"
  domain = "https://securitymastod.one"
  provider :mastodon, scope: 'read write follow', credentials: lambda { |domain, callback_url|
    app = Mastodon::REST::Client.new(base_url: "https://#{domain}").create_app('Follower Test', 'https://8ae29422.ngrok.io/auth/mastodon/callback', 'read write follow')
    return [app.client_id, app.client_secret]
  }
end
```

**Comment by matthewjamesr** [comment]
The issue has been resolved.

**Comment by uurcank** [comment]
I still get the invalid_grant error, @matthewjamesr how did you resolve this issue?
